options = {
  "Pool": [
    "9SUSDC11CORE",
    "9SUSDCCORE",
    "ADAI-AUSDC-AUSDT",
    "ALUSD-FRAX-USDC",
    "ALUSD-USDC",
    "AMDAI-AMUSDC-AMUSDT",
    "APRUSDC",
    "APUSDC-JWLAPUSDC",
    "APUSDC-USDC",
    "AUSD-USDC",
    "AUSD-USDT",
    "AUSDC",
    "AUSDT",
    "AVAI-USDC.E",
    "AVAXAI-USDC",
    "AVDAI-AVUSDC-AVUSDT",
    "AXLUSDC-USDC",
    "AXLUSDC-USDT",
    "AXLUSDC.E-USDC",
    "AXLUSDT-USDT",
    "BASEDAI-USDC",
    "BBQUSDC",
    "BBQUSDT",
    "BBUSDC",
    "BBUSDT",
    "BDAI-BUSDC-BUSDT",
    "BEEFYUSDC.E-SCUSD",
    "BOB-USDC.E",
    "BOLD-USDC",
    "BUSD-USDT",
    "BUSD-USDT-USDC-DAI",
    "CDAI-CUSDC",
    "CDAI-CUSDC-USDT",
    "CSUSDC",
    "CUSD-DAI-USDC",
    "CUSD-USDC",
    "CUSDO-USDC",
    "DAI-USDC",
    "DAI-USDC-USDT",
    "DAI-USDC-USDT-SUSD",
    "DAI-USDC.E",
    "DAI-USDC.E-USDT",
    "DAI-USDT",
    "DAI-USDT-USDC",
    "DAI.E-USDC",
    "DAI.E-USDT",
    "DEUSD-USDC",
    "DEUSD-USDT",
    "DOLA-FRAX-USDC",
    "DOLA-USDC",
    "DOLA-USDCE",
    "DUPLICATEDKEY.USDC",
    "DUSDC",
    "ELIXIRUSDC",
    "EUSD-USDC",
    "EUSDUSDC",
    "FDUSD-USDC",
    "FDUSD-USDT",
    "FEI-USDC",
    "FRAX-DAI-USDC-USDT",
    "FRAX-USDC",
    "FRAX-USDC.E",
    "FRAX-USDCE",
    "FRAX-USDT",
    "FRXUSD-USDC",
    "FRXUSD-USDT",
    "FUSDC",
    "FUSDC-USDC",
    "FUSDT",
    "FUSDT-DAI-USDC",
    "FXSABAI-USDT",
    "FXUSD-USDC",
    "FXUSDC",
    "GDAI-GUSDC-GFUSDT",
    "GHO-USDC",
    "GHO-USDC-USDT",
    "GMUSDC",
    "GMUSDC(WBTC)",
    "GTAUSDC",
    "GTEUSDC",
    "GTMSUSDC",
    "GTUSDC",
    "GTUSDCC",
    "GTUSDCCORE",
    "GTUSDCF",
    "GTUSDCP",
    "GTUSDT",
    "GUSD-USDC",
    "GUSDC",
    "GUSDC-USDC",
    "GYD-STATAGNOUSDCE",
    "GYD-USDC",
    "GYD-USDT",
    "HUSDC",
    "HUSDT",
    "IBUSDC",
    "IBUSDT",
    "IDAI-IUSDC-IUSDT",
    "INDEUSDC",
    "IONICUSDC",
    "JUSDC",
    "KUSD-UUSD-USDT",
    "KUXDUSDCORCA",
    "LISUSD-USDT",
    "LUAUSD-USDT",
    "LUSD-USDC",
    "LUSD-USDT",
    "M.USDC",
    "M.USDC-M.USDT",
    "M.USDT",
    "MC.EUSDC",
    "MEUSDC",
    "MIDASUSDC",
    "MIM-DAI-USDC-USDT",
    "MIM-DAI-USDCE-USDT",
    "MIM-FUSDT-USDC",
    "MIM-USDC",
    "MIM-USDC.E-USDT",
    "MIM-USDT",
    "MIM-USDT.E-USDC.E",
    "MOD-USDC",
    "MSUSD-USDC",
    "MSUSD-USDCE",
    "MULTIDAI-MULTIUSDC-MULTIUSDT",
    "MUSD-USDT",
    "MUSDC",
    "MWUSDC",
    "NEKOUSDC",
    "NUSDC",
    "NUSDT",
    "OUSD-USDT",
    "OUSDT",
    "OUSDT-OUSDC",
    "OUSDT-USDT",
    "PAID-USDC",
    "PINTO-USDC",
    "PUSDC",
    "PUSDT",
    "PYTHUSDC",
    "PYUSD-USDC",
    "PYUSD-USDT",
    "RAI-USDC",
    "RAI-USDC.E",
    "RE7USDC",
    "RE7USDT",
    "RESOLVUSDC",
    "REUSDC",
    "RLUSD-USDC",
    "RUSDY-USDC",
    "S*USDC",
    "SBMORPHOUSDC",
    "SDAI-STATAGNOUSDCE",
    "SMUSDC",
    "SPARKUSDC",
    "STATAARBUSDCN-GHO",
    "STATAARBUSDCN-GYD",
    "STATAARBUSDCN-STATAARBUSDT",
    "STATAARBUSDCN-USDC",
    "STATAARBUSDT-GYD",
    "STATAARBUSDTN-GYD",
    "STATAAVAUSDC-GYD",
    "STATABASUSDC-GYD",
    "STATAPOLUSDCN-GYD",
    "STATAPOLUSDCN-PAUSD",
    "STATAPOLUSDT-GYD",
    "STEAKUSDC",
    "STEAKUSDCRWA",
    "STEAKUSDT",
    "STEAKUSDTLITE",
    "SUIUSDT",
    "SUPERUSDC",
    "SUSD-DAI-USDCE-USDT",
    "SUSD-USDC",
    "SUSDCY",
    "SUSDE-USDC",
    "SUSDE-USDT",
    "SUSDZUSDC",
    "SYRUPUSDC",
    "SYRUPUSDC-USDC",
    "THUSD-DAI-USDC-USDT",
    "TUSD-USDC.E",
    "ULTRA-USDC",
    "UPUSDC",
    "USD+-FRAX-USDCE",
    "USD+-USDC",
    "USD+-USDT",
    "USD0-USDC",
    "USD0-USDT",
    "USDA-USDC",
    "USDA-USDT",
    "USDB-USDC",
    "USDC",
    "USDC+-USD+",
    "USDC-ALUSD",
    "USDC-APPEASUSDC",
    "USDC-AVAIL",
    "USDC-AXLUSDC",
    "USDC-BOB",
    "USDC-BOBA0.05%",
    "USDC-BOLD",
    "USDC-BTCUSD",
    "USDC-BUSD",
    "USDC-BUSD-USDT",
    "USDC-CDXUSD",
    "USDC-CGUSD",
    "USDC-DAI",
    "USDC-DAI-USDT-USDC",
    "USDC-DAI.E",
    "USDC-DOLA",
    "USDC-DYAD",
    "USDC-ERN",
    "USDC-EUSD",
    "USDC-FKUSD",
    "USDC-FLOAT",
    "USDC-FRAX",
    "USDC-FUSDC",
    "USDC-FXUSD",
    "USDC-GYD",
    "USDC-HAI",
    "USDC-HYUSD",
    "USDC-JWLUSD",
    "USDC-LUSD",
    "USDC-LVLUSD",
    "USDC-MONEY",
    "USDC-MSUSD",
    "USDC-NEXTUSDC",
    "USDC-RAI",
    "USDC-RLUSD",
    "USDC-SUSD",
    "USDC-SUSX",
    "USDC-SUUSD",
    "USDC-TUSD-DAI-USDT",
    "USDC-USC",
    "USDC-USD+",
    "USDC-USDBC",
    "USDC-USDC",
    "USDC-USDC+",
    "USDC-USDC-USDT-DAI",
    "USDC-USDC.E",
    "USDC-USDC.E0.01%",
    "USDC-USDCE-USDT-DAI",
    "USDC-USDE",
    "USDC-USDGLO",
    "USDC-USDM",
    "USDC-USDT",
    "USDC-USDT-OMUSD",
    "USDC-USDT-USDY",
    "USDC-USDT.E",
    "USDC-USDTB",
    "USDC-USDX",
    "USDC-USX",
    "USDC-WUSDM",
    "USDC-WUSDR",
    "USDC-XUSD",
    "USDC-YUSD",
    "USDC-ZUNUSD",
    "USDC.AXL-USDC",
    "USDC.E",
    "USDC.E(SILOVAULT)-SCUSD",
    "USDC.E-DAI.E",
    "USDC.E-PEUSD",
    "USDC.E-SCUSD",
    "USDC.E-USDC",
    "USDC.E-USDT",
    "USDC.E-USDT-SDAI",
    "USDC.E-USDT.E",
    "USDCE",
    "USDCE-SCUSD",
    "USDCE-USDT",
    "USDCE-USDT-SDAI",
    "USDCEUR",
    "USDCRWA",
    "USDD-DAI-USDC-USDT",
    "USDD-USDC.E",
    "USDD-USDT",
    "USDE-USDC",
    "USDE-USDT",
    "USDE-USDTB",
    "USDGLO-USDC",
    "USDH-USDC",
    "USDH-USDT",
    "USDL-BUSD-USDC-USDT",
    "USDL-USDC",
    "USDL-USDT",
    "USDM-USDC",
    "USDM-USDT",
    "USDS-USDC",
    "USDS-USDC.E",
    "USDT",
    "USDT-AUSD",
    "USDT-AUSD\u20ae",
    "USDT-BUSD",
    "USDT-DAI",
    "USDT-FDUSD",
    "USDT-GYD",
    "USDT-LUSD",
    "USDT-MIM",
    "USDT-MONEY",
    "USDT-MONEYCAT",
    "USDT-USC",
    "USDT-USDC",
    "USDT-USDC-DAI",
    "USDT-USDC-FDUSD",
    "USDT-USDC-WXDAI",
    "USDT-USDC.E",
    "USDT-USDCE",
    "USDT-USDE",
    "USDT-USDF",
    "USDT-USDN",
    "USDT-USDT",
    "USDT-USDT.E",
    "USDT-USDX",
    "USDT-WDAI-JWLUSD",
    "USDT.E",
    "USDT.E-USDC",
    "USDT.E-USDT",
    "USDT.KAVA",
    "USDX-USDT",
    "USDY-USDC",
    "USDZ-USDC",
    "USN-USDT",
    "USR-USDC",
    "USUALUSDC+",
    "USX-USDC",
    "UUSDC",
    "UXD-USDC",
    "VCHF-USDC",
    "WAETHUSDT-WAETHLIDOGHO-WAETHUSDC",
    "WAETHUSDT-WAETHUSDE",
    "WSTUSDT",
    "WUSD-USDT",
    "WUSDC",
    "WXDAI-USDC-USDT",
    "XAI-FRAX-USDC",
    "XAI-USDC",
    "XCUSDC",
    "XCUSDT",
    "YCDAI-YCUSDC-YCUSDT-USDP",
    "YDAI-YUSDC-YUSDT-YBUSD",
    "YUSD-USDC",
    "YUSD-USDC-USDT",
    "YUSD-USDT",
    "YVUSDC",
    "YVUSDT",
    "ZCHF-USDT",
    "ZUSDC",
    "ZUSDC-ZUSDT",
    "ZUSDT"
  ],
  "Project": [
    "AAVE V2",
    "AAVE V3",
    "ACryptoS",
    "Abracadabra Spell",
    "Across",
    "Aerodrome Slipstream",
    "Aerodrome V1",
    "Affine DeFi Earn",
    "Allbridge Classic",
    "Aloe",
    "Alpaca Leveraged Yield Farming",
    "Angle",
    "ApeSwap AMM",
    "ApeSwap Lending",
    "Aptin Finance V2",
    "Arbitrum Exchange V2",
    "Arcadia V2",
    "Aries Markets",
    "Arrakis V1",
    "Ashswap",
    "Astroport",
    "Aura",
    "Aurigami",
    "Avantis",
    "Azuro",
    "Bagful",
    "Balancer V2",
    "Balmy",
    "Bancor V3",
    "Beefy",
    "Beets DEX",
    "BendDAO Lending",
    "Benqi Lending",
    "BiFi",
    "Blend Pools",
    "CREAM Lending",
    "Cadabra Finance",
    "Camelot V2",
    "Cellana Finance",
    "Clearpool Lending",
    "Clip Finance",
    "Compound V2",
    "Compound V3",
    "Conic Finance",
    "Connext",
    "Convex Finance",
    "Credix",
    "Curve DEX",
    "DSF.Finance",
    "DeltaPrime",
    "Dolomite",
    "EVAA Protocol",
    "Echelon Market",
    "Ellipsis Finance",
    "Ensuro",
    "Equalizer Exchange",
    "Exactly",
    "Extra Finance Leverage Farming",
    "Extra Finance Xlend",
    "Ferro",
    "Fluid Lending",
    "Folks Finance Lending",
    "Folks Finance xChain",
    "Fractal Protocol",
    "Francium",
    "Fringe V1",
    "GMX V2 Perps",
    "Gains Network",
    "Gamma",
    "Gearbox",
    "Goat Protocol",
    "GoldLink",
    "Goose Finance",
    "Green Planet",
    "GrizzlyFi Hives",
    "Harmonix Finance",
    "Harvest Finance",
    "Hatom Lending",
    "HoldStation DeFutures",
    "Hop Protocol",
    "Hydradex V3",
    "Hyperdrive",
    "IPOR Derivatives",
    "IPOR Fusion",
    "Idle",
    "Impermax Finance",
    "Integral",
    "Interport Finance",
    "Ionic Protocol",
    "Joe DEX",
    "Joe V2",
    "Joe V2.1",
    "Jones DAO",
    "JustLend",
    "Kamino Lend",
    "Kamino Liquidity",
    "Keom Protocol",
    "KiloEx",
    "Kinetic",
    "Kokoa Finance",
    "Lendle",
    "LiquidSwap",
    "Liqwid",
    "Lynex V2",
    "MAHA.xyz",
    "MDEX",
    "MakerDAO",
    "Mars Lend",
    "Merkle Trade",
    "Meso Finance",
    "Minterest",
    "Moonwell",
    "Moonwell Apollo",
    "Morpho Aave",
    "Morpho Blue",
    "Morpho Compound",
    "NAVI Lending",
    "NX Finance",
    "Nabla Finance",
    "Nayms",
    "Nimbora Yield",
    "Nolus Protocol",
    "Notional V3",
    "PancakeSwap AMM",
    "Pangolin",
    "ParaSpace Lending V1",
    "Pendle",
    "Persistence DEX",
    "Pinto",
    "Pluto",
    "Prime Protocol",
    "Primex Finance",
    "QuipuSwap Stableswap",
    "Radiant V1",
    "Radiant V2",
    "Ribbon",
    "Saddle Finance",
    "SandClock",
    "Save",
    "Seamless Protocol",
    "Sherlock",
    "Silo V1",
    "Silo V2",
    "Single Finance",
    "SmartCredit",
    "Sovryn Dex",
    "Spark",
    "StakeDAO",
    "Stargate V1",
    "Starlay Finance",
    "Steer Protocol",
    "Stratum Exchange",
    "Strike",
    "Sturdy V2",
    "SushiSwap",
    "Swop",
    "Symbiosis",
    "Takara Lend",
    "Teahouse Permissionless",
    "Tectonic",
    "Tender Finance",
    "ThalaSwap",
    "The Standard",
    "Thorchain",
    "Toros",
    "Umami Finance",
    "Uniswap V2",
    "Uniswap V3",
    "Upshift",
    "VVS Standard",
    "VaultCraft",
    "Vaultka",
    "Velodrome V2",
    "Venus Core Pool",
    "Vesper",
    "Web3.world",
    "Wing Finance",
    "Wise Lending V2",
    "Wombex Finance",
    "Wompie",
    "YLDR",
    "Yama Finance",
    "Yearn Finance",
    "ZeroLend",
    "dForce",
    "fx Protocol",
    "maxAPY",
    "wefi",
    "zkSwap V2"
  ],
  "Category": [
    "Algo-Stables",
    "Bridge",
    "CDP",
    "Cross Chain Bridge",
    "DCA Tools",
    "Derivatives",
    "Dexs",
    "Farm",
    "Insurance",
    "Lending",
    "Leveraged Farming",
    "Liquidity manager",
    "Managed Token Pools",
    "NFT Lending",
    "Options Vault",
    "Prediction Market",
    "RWA Lending",
    "Uncollateralized Lending",
    "Yield",
    "Yield Aggregator"
  ],
  "Chain": [
    "APTOS",
    "Algorand",
    "Aptos",
    "Arbitrum",
    "Astar",
    "Aurora",
    "Avalanche",
    "BSC",
    "Base",
    "Bifrost Network",
    "Boba",
    "Boba_Bnb",
    "Bsquared",
    "Cardano",
    "Celo",
    "Cronos",
    "Ethereum",
    "Fantom",
    "Flare",
    "Fraxtal",
    "Gnosis",
    "Heco",
    "Hydra",
    "Kava",
    "Klaytn",
    "Linea",
    "Manta",
    "Mantle",
    "Metis",
    "Mode",
    "Moonbeam",
    "Moonriver",
    "MultiversX",
    "Neutron",
    "Nolus",
    "Ontology",
    "Op_bnb",
    "Optimism",
    "Osmosis",
    "Persistence",
    "Polygon",
    "Polygon zkEVM",
    "Rollux",
    "Rootstock",
    "Scroll",
    "Sei",
    "Solana",
    "Sonic",
    "Starknet",
    "Stellar",
    "Sui",
    "Taiko",
    "Tezos",
    "Ton",
    "Tron",
    "Unit0",
    "Venom",
    "zkSync Era"
  ],
  "Outlook": [
    "Down",
    "Up"
  ]
}